FROM rust:1.66-slim
RUN apt-get update && apt-get install -y libprotobuf-dev protobuf-compiler pkg-config libssl-dev
WORKDIR /usr/src/app

# directories must be explicitly copied to matching directories because COPY dumps all of the source directory's contents into the destination
# alternatively, we could use a .dockerignore file and then just do `COPY . .`
COPY proto ./proto
COPY src ./src
COPY build.rs Cargo* ./

RUN cargo install --locked --path .
CMD ["thespian-server"]