version: '3.9'

# consider ditching this and just making everything use localhost with port bindings
# I'm already binding to localhost so I can run jigsaw locally and debug quickly
networks:
  jigsaw_instrumentation:

services:
  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    networks:
      - jigsaw_instrumentation
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: 'http://localhost:3100/loki/api/v1/push'

  loki:
    image: grafana/loki:2.5.0
    ports:
      - 3100:3100
    volumes:
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/config.yaml
    networks:
      - jigsaw_instrumentation

  tempo:
    image: grafana/tempo:latest
    volumes:
      - ./tempo:/etc/tempo
      # - ./tempo-data:/tmp/tempo
    command: -config.file=/etc/tempo/config.yaml
    networks:
      - jigsaw_instrumentation
    # I don't need all of these, but I'm going to be experimenting for a bit at first before I can reduce them
    ports:
      - "14268:14268"  # jaeger ingest
      - "3200:3200"   # tempo
      - "4317:4317"  # otlp grpc
      - "4318:4318"  # otlp http
      - "9411:9411"   # zipkin
      - "9095:9095"   # default tempo grpc ???
    # logging:
    #   driver: loki
    #   options:
    #     loki-url: 'http://localhost:3100/loki/api/v1/push'