# this was mostly copied from the official example: https://github.com/grafana/tempo/blob/main/example/docker-compose/local/docker-compose.yaml

version: '3.9'

networks:
  thespian_instrumentation:

services:
  grafana:
    image: grafana/grafana-oss:latest
    networks:
      - thespian_instrumentation
    ports:
      - 3000:3000 # default grafana port
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources

  loki:
    image: grafana/loki:2.5.0
    networks:
      - thespian_instrumentation
    ports:
      - 3100:3100 # default loki port
    volumes:
      - ./loki:/etc/loki
    command: -config.file=/etc/loki/config.yaml

  tempo:
    image: grafana/tempo:latest
    networks:
      - thespian_instrumentation
    ports:
      - 3200:3200  # default tempo port (seems to be for queries)
      - 4317:4317  # default otlp grpc port (seems to be for ingestion)
    volumes:
      - ./tempo:/etc/tempo
    command: -config.file=/etc/tempo/config.yaml