apiVersion: 1

datasources:
- name: Tempo
  type: tempo
  access: proxy
  orgId: 1
  url: http://tempo:3200
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  apiVersion: 1
  uid: tempo
  jsonData:
    httpMethod: GET
    tracesToLogs:
      datasourceUid: 'loki'
      mappedTags: [{ key: 'service.name', value: 'service_name' }]
      mapTagNamesEnabled: true
      filterByTraceID: true
      filterBySpanID: false
- name: Loki
  type: loki
  access: proxy
  orgId: 1
  url: http://loki:3100
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
  apiVersion: 1
  uid: loki
  jsonData:
    derivedFields:
      - datasourceUid: tempo
        matcherRegex: \"(?:trace_id)\":\"(\w+)\" # thespian sends its logs in json format to loki, probably due to the tracing-loki crate
        name: trace_id
        url: $${__value.raw}