server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        grpc:

ingester:
  max_block_duration: 5m               # cut the headblock when this much time passes. this is being set for demo purposes and should probably be left alone normally

compactor:
  compaction:
    block_retention: 1h                # overall Tempo trace retention. set for demo purposes

# metrics_generator:
#   registry:
#     external_labels:
#       source: tempo
#       cluster: docker-compose
#   storage:
#     path: /tmp/tempo/generator/wal
#     remote_write:
#       - url: http://prometheus:9090/api/v1/write
#         send_exemplars: true

storage:
  trace:
    backend: local                     # backend configuration to use
    wal:
      path: /tmp/tempo/wal             # where to store the the wal locally
    local:
      path: /tmp/tempo/blocks

overrides:
  # metrics_generator_processors: [service-graphs, span-metrics] # enables metrics generator
  # these two are defaulting to 0 and causing rate limiting errors, e.g. "RATE_LIMITED: ingestion rate limit (0 bytes) exceeded while adding 727 bytes"
  # these values are overkill, but they're supposed to be the defaults
  ingestion_burst_size_bytes: 20000000
  ingestion_rate_limit_bytes: 15000000